# Generated by Django 5.0.4 on 2024-05-18 16:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('appDeustotil_Tech', '0004_alter_empleado_imagen_alter_proyecto_imagen'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.TextField(max_length=100)),
                ('password', models.TextField(max_length=100)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Usuario',
                'verbose_name_plural': 'Usuario',
                'ordering': ['-created'],
            },
        ),
    ]
