# Generated by Django 5.0.3 on 2024-05-28 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appDeustotil_Tech', '0006_cliente_alter_usuario_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empleado',
            name='created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
